name: 'Install and cache Nix'
description: 'Installs packages via the Nix package manager and caches the results.'
author: 'Rik Huijzer'

inputs:
    nix_version: 
        description: 'Nix version, defaults to `nixos-unstable`.'
        default: 'nixos-unstable'
    nix_file:
        description: 'Nix file, defaults to `default.nix`.'
        default: 'default.nix'

# For available options, see 
# https://github.com/actions/runner/blob/main/src/Runner.Worker/action_yaml.json.
runs:
    using: 'composite'
    steps: 
        - name: Install Nix package manager
          run: ./src/install_nix.sh
          shell: bash
        - name: Install via Nix
          run: ./src/install_via_nix_or_cache.sh
          shell: bash
          env:
            CACHE_HIT: ${{ steps.cache-nix-store.outputs.cache-hit }}
