name: 'Install and cache Nix'
description: 'Installs packages via the Nix package manager and caches the results.'
author: 'Rik Huijzer'

inputs:
    nix_version: 
        description: 'Nix version, defaults to `nixos-unstable`.'
        default: 'nixos-unstable'
    nix_file:
        description: 'Nix file, defaults to `default.nix`.'
        default: 'default.nix'

runs:
    using: 'composite'
    steps:
        - name: Install dependencies
          run: |
              sudo apt update 
              sudo apt install nodejs
          shell: bash

        - name: Install Nix
          # nix_path: 'nixpkgs=channel:${{ inputs.nix_version }}'
          run: |
              export INPUT_NIX_PATH="nixpkgs=channel:${{ inputs.nix_version }}"
              git clone --branch v10 https://github.com/cachix/install-nix-action /tmp/cachix
              nodejs /tmp/cachix/lib/main.js
          shell: bash
          env: 
            INPUT_SKIP_ADDING_NIXPKGS_CHANNEL: "false"
          
        - run: nix-shell -p nix-info --run "nix-info -m"
          shell: bash

        - name: Install via Nix
          run: nix-env --install --file ${{ inputs.nix_file }}
          shell: bash
