name: test

on: [push, pull_request]

jobs:
    simple:
        name: Install Python3
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install and cache Nix packages 
              uses: ./
              with:
                nix_file: 'test/simple.nix'
            - name: Test whether Ranger is installed
              run: which python3
