name: test

on: [push, pull_request]

jobs:
  simple:
    name: simple
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Nix store
        id: cache-nix-store
        uses: actions/cache@v2.1.1
        with: 
          path: |
            ~/nix/store
            ~/nix/bin
          key: nix-${{ hashFiles('test/simple.nix') }}-v2

      - name: Install via Nix or cache
        uses: ./
        with:
          nix_file: 'test/simple.nix'

      - name: Test whether simple.nix is installed
        run: hello
